{% set name = "approval-utilities" %}
{% set version = "12.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/approval_utilities-{{ version }}.tar.gz
  sha256: b69772f813f892cee0cf8652df8e0f24faa2adbf5ce493c1adbccafe2464650b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - approval_utilities
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/approvals/ApprovalTests.Python
  summary: Utilities for your production code that work well with approvaltests
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
